# pytest.ini
[pytest]
testpaths = 
    Orbitool/base/tests
    ;; Orbitool/UI/tests 
    Orbitool/UI/tests/test_timeseries_restore.py
    Orbitool/UI/tests/test_noise_damage_report.py
    Orbitool/UI/test_spectra_timeseries_migration.py
    Orbitool/UI/test_calibration_migration.py
    Orbitool/UI/test_peakfit_migration.py
    Orbitool/UI/test_main_window_migration.py
    Orbitool/UI/manager/tests
    Orbitool/UI/file_tab
    Orbitool/UI/formulas
    Orbitool/utils/files/tests
    Orbitool/models/formula/tests
    Orbitool/utils/readers/tests
    Orbitool/utils/time_format
    Orbitool/models/calibration
    Orbitool/models/file/tests
    Orbitool/models/spectrum/tests
    Orbitool/models/peakfit/normal_distribution/tests
    Orbitool/models/peakfit/tests
    Orbitool/models/workspace/tests
    utils/tests